export const products = [
  {
    id: 1,
    name: 'Dell UltraSharp 32 4K Thunderbolt Hub Monitor',
    brand: 'Dell',
    category: 'peripheral',
    price: 864,
    badge: 'new',
    image: 'https://www.bhphotovideo.com/images/images2500x2500/dell_u3225qe_ultrasharp_32_4k_thunderbolt_1846146.jpg',
    spec: '31.5" IPS Black · 4K UHD 3840x2160 · 120Hz · Thunderbolt 4 · USB-C 140W PD · 3000:1 Contrast',
    description: 'The UltraSharp U3225QE features the world\'s first enhanced IPS Black panel with stunning 3000:1 contrast ratio, 4K resolution, 120Hz refresh rate and Thunderbolt 4 connectivity with 140W power delivery.',
    inStock: true,
    stripeProductId: '',
    model: 'U3225QE',
  },
  {
    id: 2,
    name: 'Dell UltraSharp 27 4K Thunderbolt Hub Monitor',
    brand: 'Dell',
    category: 'peripheral',
    price: 638,
    badge: 'new',
    image: 'https://www.bhphotovideo.com/images/images2500x2500/dell_u2725qe_ultrasharp_27_4k_thunderbolt_1846145.jpg',
    spec: '27" IPS Black · 4K UHD 3840x2160 · 120Hz · Thunderbolt 4 · USB-C 140W PD · ComfortView Plus',
    description: 'The UltraSharp U2725QE delivers IPS Black technology with 3000:1 contrast, 4K clarity and 120Hz refresh rate in a 27" form factor — with Thunderbolt 4 hub and 140W USB-C power delivery.',
    inStock: true,
    stripeProductId: '',
    model: 'U2725QE',
  },
  {
    id: 3,
    name: 'Dell UltraSharp 40 Curved Thunderbolt Hub Monitor',
    brand: 'Dell',
    category: 'peripheral',
    price: 1577,
    badge: 'new',
    image: 'https://www.bhphotovideo.com/images/images2500x2500/dell_u4025qw_ultrasharp_40_curved_thunderbolt_1846147.jpg',
    spec: '39.7" Curved IPS · 5K2K 5120x2160 · 120Hz · Thunderbolt 4 · USB-C 140W PD · 2500R Curve',
    description: 'The UltraSharp U4025QW is a breathtaking 40" curved 5K2K display with Thunderbolt 4 hub, 120Hz refresh rate and immersive 2500R curvature — the ultimate productivity monitor.',
    inStock: true,
    stripeProductId: '',
    model: 'U4025QW',
  },
  {
    id: 4,
    name: 'Dell Pro Dock WD25',
    brand: 'Dell',
    category: 'peripheral',
    price: 151,
    badge: '',
    image: 'https://www.bhphotovideo.com/images/images2500x2500/dell_wd25_pro_dock_1779594.jpg',
    spec: 'USB-C/Thunderbolt · 100W Power Delivery · 2x USB-A · HDMI · DisplayPort · Ethernet · Audio',
    description: 'The Dell Pro Dock WD25 offers up to 100W power delivery and a wide variety of connectivity options — ideal for boosting productivity at your desk with a single cable connection.',
    inStock: true,
    stripeProductId: '',
    model: 'WD25',
  },
  {
    id: 5,
    name: 'Dell Pro Smart Dock SD25',
    brand: 'Dell',
    category: 'peripheral',
    price: 210,
    badge: '',
    image: 'https://www.bhphotovideo.com/images/images2500x2500/dell_sd25_pro_smart_dock_1779595.jpg',
    spec: 'USB-C/Thunderbolt · 130W Power Delivery · Remote Management · 2x DP · HDMI · Ethernet',
    description: 'The Dell Pro Smart Dock SD25 delivers 130W USB-C power delivery and remote management capabilities — built for enterprise IT environments that need centralised device control.',
    inStock: true,
    stripeProductId: '',
    model: 'SD25',
  },
  {
    id: 6,
    name: 'Dell Thunderbolt 4 Smart Dock',
    brand: 'Dell',
    category: 'peripheral',
    price: 280,
    badge: '',
    image: 'https://www.bhphotovideo.com/images/images2500x2500/dell_wd22tb4_thunderbolt_4_smart_dock_1700175.jpg',
    spec: 'Thunderbolt 4 · 180W System Power · 90W PD · 4x TB4 · 5x USB-A · 2x DisplayPort · Ethernet',
    description: 'The Dell Thunderbolt 4 Smart Dock WD22TB4 provides maximum connectivity with 4x Thunderbolt 4 ports, 180W system power and remote management — the complete enterprise docking solution.',
    inStock: true,
    stripeProductId: '',
    model: 'WD22TB4',
  },
  {
    id: 7,
    name: 'Dell P3225QE 32" 4K USB-C Monitor',
    brand: 'Dell',
    category: 'peripheral',
    price: 450,
    badge: '',
    image: 'https://www.bhphotovideo.com/images/images2500x2500/dell_p3225qe_32_4k_usb_c_1846148.jpg',
    spec: '31.5" IPS · 4K UHD 3840x2160 · 60Hz · USB-C 90W · USB-A Hub · HDMI · DisplayPort',
    description: 'The Dell P3225QE delivers crisp 4K resolution on a 31.5" IPS panel with USB-C 90W power delivery and a built-in USB hub — a professional display built for productivity.',
    inStock: true,
    stripeProductId: '',
    model: 'P3225QE',
  },
  {
    id: 8,
    name: 'Dell Pro 27 Plus 4K USB-C Hub Monitor',
    brand: 'Dell',
    category: 'peripheral',
    price: 377,
    badge: '',
    image: 'https://www.bhphotovideo.com/images/images2500x2500/dell_p2725qe_pro_27_plus_4k_1846144.jpg',
    spec: '27" IPS · 4K UHD 3840x2160 · 60Hz · USB-C 90W · 4x USB-A · HDMI · DP · RJ45 Ethernet',
    description: 'The Dell Pro P2725QE is a feature-rich 27" 4K monitor with USB-C hub functionality, built-in Ethernet and extensive connectivity — designed for the connected modern workplace.',
    inStock: true,
    stripeProductId: '',
    model: 'P2725QE',
  },
]

export const services = [
  {
    id: 1,
    title: 'B2B Hardware Procurement',
    icon: 'laptop',
    image: '/images/services/procurement.jpg',
    description: 'Dell, HP, Lenovo and more — tailored enterprise procurement with flexible models for businesses of all sizes. From a single device to a full organisation rollout.',
    features: ['Custom procurement proposals', 'Multi-brand sourcing', 'Bulk pricing available', 'Dedicated account manager'],
  },
  {
    id: 2,
    title: 'Network & Hardware Installation',
    icon: 'network',
    image: '/images/services/installation.jpg',
    description: 'End-to-end installation, configuration and commissioning of network infrastructure and enterprise hardware across your UK premises.',
    features: ['On-site installation', 'Network configuration', 'Cabling & infrastructure', 'Post-install support'],
  },
  {
    id: 3,
    title: 'IT Leasing Services',
    icon: 'chart',
    image: '/images/services/leasing.jpg',
    description: 'Flexible subscription and leasing models — preserve capital, stay current with technology and scale your hardware on your terms.',
    features: ['Monthly & annual plans', 'Hardware refresh cycles', 'Preserve capital expenditure', 'Upgrade at end of term'],
  },
  {
    id: 4,
    title: 'Data Wiping & Asset Recertification',
    icon: 'recycle',
    image: '/images/services/recertification.jpg',
    description: 'Certified secure data wiping and hardware recertification — responsible disposal, resale-ready assets and full audit trails for your business.',
    features: ['Certified data destruction', 'GDPR-compliant process', 'Asset recertification', 'Full audit trail provided'],
  },
]

export const categories = [
  { id: 'laptop', label: 'Laptops', icon: 'laptop', bg: '#D6E8F7' },
  { id: 'desktop', label: 'Desktops & All-in-Ones', icon: 'desktop', bg: '#D9E6F5' },
  { id: 'server', label: 'Servers', icon: 'server', bg: '#CDD8EF' },
  { id: 'peripheral', label: 'Monitors & Peripherals', icon: 'monitor', bg: '#C8D5E8' },
  { id: 'networking', label: 'Networking', icon: 'network', bg: '#BFD2E9' },
  { id: 'storage', label: 'Data Storage', icon: 'database', bg: '#C2D8EF' },
  { id: 'workstation', label: 'Workstations', icon: 'cpu', bg: '#BDD0E8' },
  { id: 'recertified', label: 'Recertified Assets', icon: 'recycle', bg: '#BFCDE6' },
]

export const heroDevices = [
  {
    category: 'Dell UltraSharp Series',
    name: 'Clarity at every desk.',
    name2: 'See more. Do more.',
    desc: '4K and 5K professional displays with Thunderbolt 4 hub functionality and up to 140W USB-C power delivery.',
    price: '£638',
    spec: '4K IPS Black · 120Hz · Thunderbolt 4 · 140W PD',
    type: 'monitor',
    chip1Label: 'Resolution', chip1Val: '4K / 5K IPS',
    chip2Label: 'Starting from', chip2Val: '£638 +VAT',
    chip3Label: 'USB-C Power', chip3Val: '140W Delivery',
  },
  {
    category: 'Dell Docking Solutions',
    name: 'One cable.',
    name2: 'Everything connected.',
    desc: 'Dell Pro and Thunderbolt 4 docks — up to 180W system power, enterprise remote management and full connectivity.',
    price: '£151',
    spec: 'Thunderbolt 4 · Up to 180W · Remote Management',
    type: 'server',
    chip1Label: 'Connectivity', chip1Val: 'Thunderbolt 4',
    chip2Label: 'Starting from', chip2Val: '£151 +VAT',
    chip3Label: 'System Power', chip3Val: 'Up to 180W',
  },
  {
    category: 'Dell Pro Monitor Series',
    name: 'Professional displays.',
    name2: 'Built for business.',
    desc: 'Dell Pro monitors with 4K resolution, USB-C hub functionality and built-in Ethernet — one cable does it all.',
    price: '£377',
    spec: '4K UHD · USB-C 90W · Built-in Ethernet · USB Hub',
    type: 'laptop',
    chip1Label: 'Resolution', chip1Val: '4K UHD IPS',
    chip2Label: 'Starting from', chip2Val: '£377 +VAT',
    chip3Label: 'USB-C Power', chip3Val: '90W Delivery',
  },
]

export const companyInfo = {
  name: 'IT4Everyone Ltd',
  trading: 'IT4EVERYONE LTD',
  tagline: 'Your Dell Specialist',
  phone1: '01296 816012',
  phone2: '07518 577981',
  email: 'info@it4evo.co.uk',
  website: 'www.it4eo.co.uk',
  address: 'Regus The Gatehouse, Gatehouse Way, Aylesbury, Buckinghamshire',
  founded: '2020',
}
