export const products = [
  {
    id: 1,
    name: 'Dell Latitude 5540',
    brand: 'Dell',
    category: 'laptop',
    price: 899,
    badge: 'new',
    image: '/images/products/dell-latitude-5540.jpg',
    spec: 'Intel Core i7-1355U · 16GB DDR5 · 512GB NVMe SSD · Win 11 Pro · 15.6" FHD',
    description: 'Business-grade reliability with military-spec durability. Intel Core i7, 16GB RAM and a stunning FHD display — built for the modern workplace.',
    inStock: true,
    stripeProductId: '',
  },
  {
    id: 2,
    name: 'Dell OptiPlex 7010 Tower',
    brand: 'Dell',
    category: 'desktop',
    price: 749,
    badge: '',
    image: '/images/products/dell-optiplex-7010.jpg',
    spec: 'Intel Core i5-13500 · 8GB DDR4 · 256GB SSD · Win 11 Pro',
    description: 'A powerful, compact desktop built for business. Easily upgradable and engineered for performance under any enterprise workload.',
    inStock: true,
    stripeProductId: '',
  },
  {
    id: 3,
    name: 'HP EliteBook 840 G10',
    brand: 'HP',
    category: 'laptop',
    price: 1149,
    badge: 'sale',
    image: '/images/products/hp-elitebook-840.jpg',
    spec: 'Intel Core i7-1355U · 16GB · 1TB SSD · Win 11 Pro · 14" FHD IPS',
    description: 'HP\u2019s flagship business laptop — ultra-secure, ultra-slim, and loaded with enterprise features including HP Wolf Security.',
    inStock: true,
    stripeProductId: '',
  },
  {
    id: 4,
    name: 'Lenovo ThinkPad X1 Carbon',
    brand: 'Lenovo',
    category: 'laptop',
    price: 1299,
    badge: 'b2b',
    image: '/images/products/lenovo-thinkpad-x1.jpg',
    spec: 'Intel Core i7-1365U · 32GB · 1TB SSD · LTE Ready · Win 11 Pro',
    description: 'The gold standard for business mobility. Featherlight at under 1.12kg, with Intel EVO certification and built-in LTE connectivity.',
    inStock: true,
    stripeProductId: '',
  },
  {
    id: 5,
    name: 'Dell PowerEdge R350',
    brand: 'Dell',
    category: 'server',
    price: 2499,
    badge: '',
    image: '/images/products/dell-poweredge-r350.jpg',
    spec: 'Intel Xeon E-2300 · 16GB ECC RAM · 2TB RAID · 1U Rack',
    description: 'Entry-level rack server built for small to mid-size workloads. Reliable, scalable and backed by Dell ProSupport.',
    inStock: true,
    stripeProductId: '',
  },
  {
    id: 6,
    name: 'HP ProDesk 600 G9 SFF',
    brand: 'HP',
    category: 'desktop',
    price: 699,
    badge: 'sale',
    image: '/images/products/hp-prodesk-600.jpg',
    spec: 'Intel Core i5-12500 · 8GB DDR5 · 256GB SSD · Win 11 Pro · SFF',
    description: 'Compact, powerful and energy-efficient — the HP ProDesk 600 is the ideal desktop for space-conscious businesses.',
    inStock: true,
    stripeProductId: '',
  },
  {
    id: 7,
    name: 'Lenovo ThinkCentre M90q',
    brand: 'Lenovo',
    category: 'desktop',
    price: 629,
    badge: '',
    image: '/images/products/lenovo-thinkcentre-m90q.jpg',
    spec: 'Intel Core i5-12500 · 8GB · 512GB SSD · Tiny Form Factor',
    description: 'Incredibly compact without sacrificing power. The M90q fits anywhere and delivers full desktop performance for any business need.',
    inStock: true,
    stripeProductId: '',
  },
  {
    id: 8,
    name: 'Dell UltraSharp 27" U2722D',
    brand: 'Dell',
    category: 'peripheral',
    price: 399,
    badge: 'new',
    image: '/images/products/dell-u2722d.jpg',
    spec: '4K IPS · USB-C 90W · Height Adjustable · 60Hz · HDMI/DP',
    description: 'Stunning 4K IPS clarity with USB-C power delivery — the definitive professional monitor for design, data and productivity.',
    inStock: true,
    stripeProductId: '',
  },
  {
    id: 9,
    name: 'HP EliteDisplay E243 24"',
    brand: 'HP',
    category: 'peripheral',
    price: 249,
    badge: '',
    image: '/images/products/hp-e243.jpg',
    spec: 'FHD IPS · USB-C · Built-in USB Hub · VESA Mount',
    description: 'A reliable, sharp FHD IPS display with USB-C and a built-in USB hub. The smart choice for multi-monitor enterprise setups.',
    inStock: true,
    stripeProductId: '',
  }
]

export const services = [
  {
    id: 1,
    title: 'B2B Hardware Procurement',
    icon: 'laptop',
    image: '/images/services/procurement.jpg',
    description: 'Dell, HP, Lenovo and more — tailored enterprise procurement with flexible models for businesses of all sizes. From a single device to a full organisation rollout.',
    features: ['Custom procurement proposals', 'Multi-brand sourcing', 'Bulk pricing available', 'Dedicated account manager'],
  },
  {
    id: 2,
    title: 'Network & Hardware Installation',
    icon: 'network',
    image: '/images/services/installation.jpg',
    description: 'End-to-end installation, configuration and commissioning of network infrastructure and enterprise hardware across your UK premises.',
    features: ['On-site installation', 'Network configuration', 'Cabling & infrastructure', 'Post-install support'],
  },
  {
    id: 3,
    title: 'IT Leasing Services',
    icon: 'chart',
    image: '/images/services/leasing.jpg',
    description: 'Flexible subscription and leasing models — preserve capital, stay current with technology and scale your hardware on your terms.',
    features: ['Monthly & annual plans', 'Hardware refresh cycles', 'Preserve capital expenditure', 'Upgrade at end of term'],
  },
  {
    id: 4,
    title: 'Data Wiping & Asset Recertification',
    icon: 'recycle',
    image: '/images/services/recertification.jpg',
    description: 'Certified secure data wiping and hardware recertification — responsible disposal, resale-ready assets and full audit trails for your business.',
    features: ['Certified data destruction', 'GDPR-compliant process', 'Asset recertification', 'Full audit trail provided'],
  },
]

export const categories = [
  { id: 'laptop', label: 'Laptops', icon: 'laptop', bg: '#D6E8F7' },
  { id: 'desktop', label: 'Desktops & All-in-Ones', icon: 'desktop', bg: '#D9E6F5' },
  { id: 'server', label: 'Servers', icon: 'server', bg: '#CDD8EF' },
  { id: 'peripheral', label: 'Monitors & Peripherals', icon: 'monitor', bg: '#C8D5E8' },
  { id: 'networking', label: 'Networking', icon: 'network', bg: '#BFD2E9' },
  { id: 'storage', label: 'Data Storage', icon: 'database', bg: '#C2D8EF' },
  { id: 'workstation', label: 'Workstations', icon: 'cpu', bg: '#BDD0E8' },
  { id: 'recertified', label: 'Recertified Assets', icon: 'recycle', bg: '#BFCDE6' },
]

export const heroDevices = [
  {
    category: 'Dell Latitude Series',
    name: 'Built for business.',
    name2: 'Ready for anything.',
    desc: 'Enterprise-grade reliability with Intel Core i7, military-spec durability and Windows 11 Pro — with dedicated account support.',
    price: '£899',
    spec: 'Intel Core i7 · 16GB · 512GB NVMe · Win 11 Pro',
    type: 'laptop',
    chip1Label: 'Processor', chip1Val: 'Intel Core i7',
    chip2Label: 'Starting from', chip2Val: '£899 +VAT',
    chip3Label: 'Storage', chip3Val: '512GB NVMe',
  },
  {
    category: 'Dell PowerEdge Series',
    name: 'Enterprise servers.',
    name2: 'Scale without limits.',
    desc: 'From entry-level rack servers to full data centre deployments — procured, delivered and installed across the UK.',
    price: '£2,499',
    spec: 'Xeon E-2300 · 16GB ECC · 2TB RAID · 1U Rack',
    type: 'server',
    chip1Label: 'Processor', chip1Val: 'Intel Xeon',
    chip2Label: 'Starting from', chip2Val: '£2,499 +VAT',
    chip3Label: 'Memory', chip3Val: '16GB ECC',
  },
  {
    category: 'Dell UltraSharp Series',
    name: 'Clarity at every desk.',
    name2: 'See more. Do more.',
    desc: '4K IPS professional displays with USB-C power delivery — completing the perfect enterprise workstation setup.',
    price: '£399',
    spec: '4K IPS · USB-C 90W · Height Adj · 60Hz',
    type: 'monitor',
    chip1Label: 'Resolution', chip1Val: '4K UHD IPS',
    chip2Label: 'Starting from', chip2Val: '£399 +VAT',
    chip3Label: 'USB-C Power', chip3Val: '90W Delivery',
  },
]

export const companyInfo = {
  name: 'IT4Everyone Ltd',
  trading: 'IT4EVERYONE LTD',
  tagline: 'Your Dell Specialist',
  phone1: '01296 816012',
  phone2: '07518 577981',
  email: 'sraper@it4eo.co.uk',
  website: 'www.it4eo.co.uk',
  address: 'Regus The Gatehouse, Gatehouse Way, Aylesbury, Buckinghamshire',
  founded: '2020',
  directors: [
    {
      name: 'Stephen Raper',
      initials: 'SR',
      role: 'Founder & Sales Director',
      bio: 'Founded IT4Everyone in 2020 with a mission to make enterprise-grade IT procurement accessible to UK businesses of all sizes.',
      phone: '01296 816012',
      mobile: '07518 577981',
      email: 'sraper@it4eo.co.uk',
    },
    {
      name: 'Christopher Reeves',
      initials: 'CR',
      role: 'Board Director',
      bio: 'Joined the board in 2023 following rapid company growth, bringing strategic direction to IT4Everyone\'s B2B enterprise expansion.',
    },
  ],
}
